<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>CITAS_APP</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Controllers\MedicoController.cs" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="Data\Admins,json" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Controllers\MedicoController.cs" />
  </ItemGroup>

</Project>
